### ISSUE TITLE
elm compiler error when running the app

### ISSUE THREAD

**Issue by ghost** [bartekgorny/pointing-poker-elm#1]
webpack is watching the files…

/Users/b/repos/common/pointing-poker-elm/assets/node_modules/node-elm-compiler/dist/index.js:85
            .on('error', function (err) { throw (err); });
                                          ^

Error: spawn elm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[error] Task #PID<0.572.0> started from PokerWeb.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix 1.4.17) lib/phoenix/endpoint/watcher.ex:29: Phoenix.Endpoint.Watcher.watch/3
    (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["node", ["node_modules/webpack/bin/webpack.js", "--mode", "development", "--watch-stdin"], [cd: "/Users/b/repos/common/pointing-poker-elm/assets"]]
 
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution

**Comment by bartekgorny** [comment]
Maybe you don't have an elm compiler - you can get it [here](https://guide.elm-lang.org/install/elm.html).
